[package]
name = "lean-squares-in-fibonacci"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "89431cf4f01ff0f6b4005f96795a23571258cbf0"}
