[package]
name = "lean-squares-in-fibonacci"
version = "0.1"
lean_version = "leanprover-community/lean:3.5.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2d6556dd69faddc92baacaf97d6c0fb39a804b19"}
